export const state = {
  authed: false,
  student: {},
  courses: [],
  businesses: [],
  studentListFilter: 'business',
  appView: 'studentHome',
  adminName: '',
  sidebarOpen: false,
  notification: {
    type: '',
    message: ''
  },
  activeUnit: {},
  activeCard: {},
  activeStudentProfile: {},
  activeBusinessProfile: {
    students: []
  },
  activeStudentCourse: {},
  activeStudentCard: {},
  user: {},
  breadcrumbs: [],
  modals: {
    unit: false,
    student: false,
    course: false,
    business: false,
    card: false,
    addStudentCourse: false,
    removeStudentCourse: false,
    removeCourse: false,
    removeStudent: false,
    removeUnit: false,
    removeCard: false,
    removeVideo: false,
  },
  removeCourseId: null,
  removeUnitId: null,
  removeCardId: null,
  addCardUnitId: null,
}
