export const state = {
  authed: false,
  courses: [],
  businesses: [],
  studentListFilter: 'business',
  appView: 'studentHome',
  activeCourse: {},
  activeUnit: {},
  activeCard: {},
  activeStudentProfile: {},
  activeBusinessProfile: {},
  activeStudentCourse: {},
  activeStudentCard: {},
  user: {},
  breadcrumbs: [],
  modals: {
    unit: false,
    student: false,
    course: false,
    business: false,
    card: false,
    addStudentCourse: false,
    removeStudentCourse: false,
    removeCourse: false,
    removeUnit: false,
    removeCard: false,
  },
  removeCourseId: null,
  removeUnitId: null,
  removeCardId: null,
}
